security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '$2y$13$JKEXVnwpNJBfq9tCbIUOS.cHcpxnA33WcKz3H52PAnxI31SwVlY/y' 
                        roles: ['ROLE_ADMIN']
                    user:
                        password: '$2y$13$M6SbQokykBvhkTj86tjRE.Sn7igx4JGk0Ms6BN..zFHaEl7.bFuGu'
                        roles: ['ROLE_USER']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: in_memory
            http_basic: ~
            logout:
                path: app_logout

    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }
